#!/bin/sh

state="$(nmcli radio wifi 2>/dev/null)"

case $state in
    enabled)
        nmcli radio wifi off && pkill -RTMIN+9 -x waybar 2>/dev/null || :
        ;;
    disabled)
        nmcli radio wifi on && pkill -RTMIN+9 -x waybar 2>/dev/null || :
        ;;
    *)
        notify-send -u critical "Wi-Fi state unavailable"
        exit 1
        ;;
esac
