#!/bin/sh

powered="$(bluetoothctl show 2>/dev/null | awk '/Powered:/ { print $2; exit }')"

case $powered in
    yes)
        bluetoothctl power off >/dev/null
        ;;
    no)
        bluetoothctl power on >/dev/null
        ;;
    *)
        notify-send -u critical "Bluetooth controller unavailable"
        exit 1
        ;;
esac
