add_newline = false
format = "$username$hostname$directory$git_branch$git_status$python$cmd_duration$status$character"

[username]
show_always = true
style_user = "bold #E36464"
style_root = "bold red"
format = "[$user]($style)"

[hostname]
ssh_only = false
style = "bold #E36464"
format = "[@$hostname]($style) "

[directory]
style = "bold #56B6C2"
truncation_length = 3
truncation_symbol = "…/"
format = "[$path]($style) "

[git_branch]
symbol = ""
style = "bold #DDB15F"
format = "[($branch)]($style) "

[git_status]
style = "bold #DDB15F"
format = "[$all_status$ahead_behind]($style) "

[python]
style = "bold #62ED8B"
version_format = "${major}.${minor}"
format = "[($version)]($style) "

[cmd_duration]
min_time = 0
show_milliseconds = true
style = "bold #D4AAFC"
format = "[$duration]($style) "

[status]
disabled = false
symbol = "\uf00d"
style = "bold #E36464"
format = "[$symbol]($style) "

[character]
success_symbol = "[⮞](bold #D4AAFC)"
error_symbol = "[⮞](bold #E36464)"
vimcmd_symbol = "[⮜](bold #56B6C2)"
